// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'vibebuild_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String AUTH_LOGO_TRANSPARENT = 'assets/branding/auth_logo_transparent.png';
  static const String LANUCH = 'assets/branding/lanuch.mp4';
}
