-- ============================================================
-- 为表与字段补充中文注释（MySQL 8.0+）
-- 可重复执行：仅更新元数据，不改变数据
-- 须在首条含中文语句前设置连接字符集，否则 COMMENT 可能乱码
-- ============================================================

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET CHARACTER SET utf8mb4;

-- ---------- users ----------
ALTER TABLE users COMMENT = '用户账户与资料';
ALTER TABLE users
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '对外暴露的用户唯一标识',
    MODIFY COLUMN phone VARCHAR(20) NULL COMMENT '登录手机号',
    MODIFY COLUMN phone_hash VARCHAR(64) NULL COMMENT '手机号 SHA256，用于验证码等查询',
    MODIFY COLUMN password_hash VARCHAR(255) NULL COMMENT '密码哈希（若启用密码登录）',
    MODIFY COLUMN wechat_openid VARCHAR(128) NULL COMMENT '微信 OpenID',
    MODIFY COLUMN wechat_unionid VARCHAR(128) NULL COMMENT '微信 UnionID',
    MODIFY COLUMN nickname VARCHAR(50) NOT NULL COMMENT '昵称',
    MODIFY COLUMN avatar_url VARCHAR(512) NULL COMMENT '头像 URL',
    MODIFY COLUMN role SMALLINT NOT NULL DEFAULT 0 COMMENT '角色：0普通 1需求方 2专家等，见业务枚举',
    MODIFY COLUMN gender SMALLINT NULL DEFAULT 0 COMMENT '性别：0未知 1男 2女等',
    MODIFY COLUMN bio TEXT NULL COMMENT '个人简介',
    MODIFY COLUMN city VARCHAR(50) NULL COMMENT '所在城市',
    MODIFY COLUMN contact_phone VARCHAR(20) NULL COMMENT '对外联系手机号（可与登录号不同）',
    MODIFY COLUMN real_name VARCHAR(50) NULL COMMENT '真实姓名',
    MODIFY COLUMN id_card_no VARCHAR(255) NULL COMMENT '证件号（加密或脱敏存储）',
    MODIFY COLUMN is_verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否完成实名/资质认证',
    MODIFY COLUMN verified_at DATETIME NULL COMMENT '认证通过时间',
    MODIFY COLUMN hourly_rate DECIMAL(10,2) NULL COMMENT '专家时薪报价',
    MODIFY COLUMN available_status SMALLINT NULL DEFAULT 1 COMMENT '接单/在线状态',
    MODIFY COLUMN response_time_avg INT NULL DEFAULT 0 COMMENT '平均响应时间（分钟等，业务定义）',
    MODIFY COLUMN credit_score INT NOT NULL DEFAULT 500 COMMENT '信用分',
    MODIFY COLUMN level SMALLINT NOT NULL DEFAULT 1 COMMENT '用户等级',
    MODIFY COLUMN total_orders INT NOT NULL DEFAULT 0 COMMENT '累计订单数',
    MODIFY COLUMN completed_orders INT NOT NULL DEFAULT 0 COMMENT '已完成订单数',
    MODIFY COLUMN completion_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '完成率百分比',
    MODIFY COLUMN avg_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00 COMMENT '平均评分',
    MODIFY COLUMN total_earnings DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计收入',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '账号状态：1正常等',
    MODIFY COLUMN onboarding_status SMALLINT NOT NULL DEFAULT 2 COMMENT '入驻审核：1待审 2通过 3拒绝',
    MODIFY COLUMN invite_code_id BIGINT NULL COMMENT '注册使用的邀请码记录 ID',
    MODIFY COLUMN onboarding_reject_reason VARCHAR(500) NULL COMMENT '入驻驳回原因',
    MODIFY COLUMN onboarding_reviewed_at DATETIME NULL COMMENT '入驻审核时间',
    MODIFY COLUMN onboarding_reviewer_id BIGINT NULL COMMENT '审核管理员用户 ID',
    MODIFY COLUMN resume_url VARCHAR(512) NULL COMMENT '入驻材料：简历或作品链接',
    MODIFY COLUMN onboarding_application_note TEXT NULL COMMENT '入驻申请说明',
    MODIFY COLUMN onboarding_submitted_at DATETIME NULL COMMENT '提交入驻材料时间',
    MODIFY COLUMN freeze_reason VARCHAR(200) NULL COMMENT '冻结原因',
    MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最近登录时间',
    MODIFY COLUMN last_login_ip VARCHAR(45) NULL COMMENT '最近登录 IP',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- skills ----------
ALTER TABLE skills COMMENT = '技能标签字典';
ALTER TABLE skills
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '技能名称',
    MODIFY COLUMN category VARCHAR(50) NOT NULL COMMENT '技能分类',
    MODIFY COLUMN icon_url VARCHAR(512) NULL COMMENT '图标 URL',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序权重，越大越靠前',
    MODIFY COLUMN is_hot TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否热门',
    MODIFY COLUMN usage_count INT NOT NULL DEFAULT 0 COMMENT '被用户选用次数',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- user_skills ----------
ALTER TABLE user_skills COMMENT = '用户与技能多对多';
ALTER TABLE user_skills
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN skill_id BIGINT NOT NULL COMMENT '技能 ID',
    MODIFY COLUMN proficiency SMALLINT NULL DEFAULT 3 COMMENT '熟练度 1-5',
    MODIFY COLUMN years_of_experience SMALLINT NULL DEFAULT 0 COMMENT '相关年限',
    MODIFY COLUMN is_primary TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主技能',
    MODIFY COLUMN is_certified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否平台认证',
    MODIFY COLUMN certified_at DATETIME NULL COMMENT '认证时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- role_tags ----------
ALTER TABLE role_tags COMMENT = '角色/身份标签字典';
ALTER TABLE role_tags
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '标签名',
    MODIFY COLUMN description VARCHAR(200) NULL COMMENT '描述',
    MODIFY COLUMN icon_url VARCHAR(512) NULL COMMENT '图标 URL',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- user_role_tags ----------
ALTER TABLE user_role_tags COMMENT = '用户与角色标签关联';
ALTER TABLE user_role_tags
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN role_tag_id BIGINT NOT NULL COMMENT '角色标签 ID',
    MODIFY COLUMN is_primary TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主标签',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- portfolios ----------
ALTER TABLE portfolios COMMENT = '用户作品集';
ALTER TABLE portfolios
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '作品 UUID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '作者用户 ID',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '关联平台项目 ID（若有）',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题',
    MODIFY COLUMN description TEXT NULL COMMENT '描述',
    MODIFY COLUMN category VARCHAR(50) NOT NULL COMMENT '分类',
    MODIFY COLUMN cover_url VARCHAR(512) NULL COMMENT '封面图 URL',
    MODIFY COLUMN preview_url VARCHAR(512) NULL COMMENT '预览链接',
    MODIFY COLUMN tech_stack JSON NULL COMMENT '技术栈 JSON 数组',
    MODIFY COLUMN images JSON NULL COMMENT '图片 URL 列表 JSON',
    MODIFY COLUMN demo_video_url VARCHAR(512) NULL COMMENT '演示视频 URL',
    MODIFY COLUMN is_platform_certified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否平台认证作品',
    MODIFY COLUMN certified_at DATETIME NULL COMMENT '认证时间',
    MODIFY COLUMN view_count INT NOT NULL DEFAULT 0 COMMENT '浏览量',
    MODIFY COLUMN like_count INT NOT NULL DEFAULT 0 COMMENT '点赞数',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：1上架等',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- sms_codes ----------
ALTER TABLE sms_codes COMMENT = '短信验证码记录';
ALTER TABLE sms_codes
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN phone_hash VARCHAR(64) NOT NULL COMMENT '手机号哈希',
    MODIFY COLUMN code VARCHAR(6) NOT NULL COMMENT '验证码',
    MODIFY COLUMN purpose SMALLINT NOT NULL COMMENT '用途：登录/注册等',
    MODIFY COLUMN is_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已使用',
    MODIFY COLUMN expire_at DATETIME NOT NULL COMMENT '过期时间',
    MODIFY COLUMN ip_address VARCHAR(45) NULL COMMENT '请求 IP',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- user_devices ----------
ALTER TABLE user_devices COMMENT = '用户登录设备';
ALTER TABLE user_devices
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN device_id VARCHAR(128) NOT NULL COMMENT '设备唯一标识',
    MODIFY COLUMN device_type VARCHAR(20) NOT NULL COMMENT '设备类型 ios/android/web 等',
    MODIFY COLUMN device_name VARCHAR(100) NULL COMMENT '设备名称',
    MODIFY COLUMN push_token VARCHAR(512) NULL COMMENT '推送 Token',
    MODIFY COLUMN app_version VARCHAR(20) NULL COMMENT 'App 版本',
    MODIFY COLUMN os_version VARCHAR(20) NULL COMMENT '系统版本',
    MODIFY COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否仍有效',
    MODIFY COLUMN last_active_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近活跃时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次记录时间';

-- ---------- teams ----------
ALTER TABLE teams COMMENT = '团队（专家小队）';
ALTER TABLE teams
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '团队 UUID',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '团队名称',
    MODIFY COLUMN leader_id BIGINT NOT NULL COMMENT '队长用户 ID',
    MODIFY COLUMN avatar_url VARCHAR(512) NULL COMMENT '团队头像',
    MODIFY COLUMN description TEXT NULL COMMENT '团队介绍',
    MODIFY COLUMN team_type SMALLINT NOT NULL DEFAULT 1 COMMENT '团队类型',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '关联项目（若因项目组建）',
    MODIFY COLUMN skills_coverage JSON NULL COMMENT '技能覆盖 JSON',
    MODIFY COLUMN member_count INT NOT NULL DEFAULT 1 COMMENT '成员数',
    MODIFY COLUMN avg_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00 COMMENT '平均评分',
    MODIFY COLUMN total_projects INT NOT NULL DEFAULT 0 COMMENT '参与项目数',
    MODIFY COLUMN total_earnings DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '团队累计收入',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态',
    MODIFY COLUMN disbanded_at DATETIME NULL COMMENT '解散时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- team_members ----------
ALTER TABLE team_members COMMENT = '团队成员与分润比例';
ALTER TABLE team_members
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN team_id BIGINT NOT NULL COMMENT '团队 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '成员用户 ID',
    MODIFY COLUMN role_in_team VARCHAR(50) NOT NULL COMMENT '队内角色',
    MODIFY COLUMN split_ratio DECIMAL(5,2) NOT NULL COMMENT '分账比例（百分比或约定小数）',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '成员状态',
    MODIFY COLUMN joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    MODIFY COLUMN left_at DATETIME NULL COMMENT '离开时间';

-- ---------- team_invites ----------
ALTER TABLE team_invites COMMENT = '团队邀请记录';
ALTER TABLE team_invites
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '邀请 UUID',
    MODIFY COLUMN team_id BIGINT NOT NULL COMMENT '团队 ID',
    MODIFY COLUMN inviter_id BIGINT NOT NULL COMMENT '邀请人用户 ID',
    MODIFY COLUMN invitee_id BIGINT NOT NULL COMMENT '被邀请人用户 ID',
    MODIFY COLUMN role_in_team VARCHAR(50) NOT NULL COMMENT '拟担任队内角色',
    MODIFY COLUMN split_ratio DECIMAL(5,2) NOT NULL COMMENT '拟分润比例',
    MODIFY COLUMN message TEXT NULL COMMENT '邀请附言',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '邀请状态：待处理/已接受等',
    MODIFY COLUMN expire_at DATETIME NOT NULL COMMENT '过期时间',
    MODIFY COLUMN responded_at DATETIME NULL COMMENT '响应时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- team_posts ----------
ALTER TABLE team_posts COMMENT = '组队大厅帖子';
ALTER TABLE team_posts
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '帖子 UUID',
    MODIFY COLUMN author_id BIGINT NOT NULL COMMENT '发布人用户 ID',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '关联项目',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题',
    MODIFY COLUMN description TEXT NOT NULL COMMENT '正文描述',
    MODIFY COLUMN needed_roles JSON NULL COMMENT '需要的角色 JSON',
    MODIFY COLUMN required_skills JSON NULL COMMENT '需要的技能 JSON',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '帖子状态',
    MODIFY COLUMN view_count INT NOT NULL DEFAULT 0 COMMENT '浏览量',
    MODIFY COLUMN apply_count INT NOT NULL DEFAULT 0 COMMENT '申请/意向数',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- projects ----------
ALTER TABLE projects COMMENT = '需求/项目';
ALTER TABLE projects
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '项目 UUID',
    MODIFY COLUMN owner_id BIGINT NOT NULL COMMENT '需求方用户 ID',
    MODIFY COLUMN provider_id BIGINT NULL COMMENT '成交后服务方用户 ID',
    MODIFY COLUMN team_id BIGINT NULL COMMENT '服务团队 ID',
    MODIFY COLUMN bid_id BIGINT NULL COMMENT '中标投标 ID',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '需求标题',
    MODIFY COLUMN description TEXT NOT NULL COMMENT '需求描述',
    MODIFY COLUMN category VARCHAR(50) NOT NULL COMMENT '分类：data/dev/visual/solution 等',
    MODIFY COLUMN template_type VARCHAR(50) NULL COMMENT 'PRD 模板类型',
    MODIFY COLUMN ai_prd JSON NULL COMMENT 'AI 生成 PRD 草稿',
    MODIFY COLUMN ai_estimate JSON NULL COMMENT 'AI 估价信息',
    MODIFY COLUMN confirmed_prd JSON NULL COMMENT '确认后的 PRD',
    MODIFY COLUMN budget_min DECIMAL(10,2) NULL COMMENT '预算下限',
    MODIFY COLUMN budget_max DECIMAL(10,2) NULL COMMENT '预算上限',
    MODIFY COLUMN agreed_price DECIMAL(10,2) NULL COMMENT '撮合成交价',
    MODIFY COLUMN deadline DATE NULL COMMENT '期望交付日期',
    MODIFY COLUMN agreed_days INT NULL COMMENT '约定工期天数',
    MODIFY COLUMN start_date DATE NULL COMMENT '实际开始日期',
    MODIFY COLUMN actual_end_date DATE NULL COMMENT '实际结束日期',
    MODIFY COLUMN complexity VARCHAR(10) NULL COMMENT '复杂度标记',
    MODIFY COLUMN tech_requirements JSON NULL COMMENT '技术要求 JSON',
    MODIFY COLUMN attachments JSON NULL COMMENT '附件元数据 JSON',
    MODIFY COLUMN match_mode SMALLINT NOT NULL DEFAULT 1 COMMENT '撮合模式',
    MODIFY COLUMN progress SMALLINT NOT NULL DEFAULT 0 COMMENT '进度 0-100',
    MODIFY COLUMN current_milestone_id BIGINT NULL COMMENT '当前里程碑 ID',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '项目状态：草稿/发布/撮合中/进行中等',
    MODIFY COLUMN close_reason VARCHAR(200) NULL COMMENT '关闭原因',
    MODIFY COLUMN view_count INT NOT NULL DEFAULT 0 COMMENT '浏览量',
    MODIFY COLUMN bid_count INT NOT NULL DEFAULT 0 COMMENT '投标数',
    MODIFY COLUMN favorite_count INT NOT NULL DEFAULT 0 COMMENT '收藏数',
    MODIFY COLUMN published_at DATETIME NULL COMMENT '发布时间',
    MODIFY COLUMN matched_at DATETIME NULL COMMENT '撮合成功时间',
    MODIFY COLUMN started_at DATETIME NULL COMMENT '开工时间',
    MODIFY COLUMN completed_at DATETIME NULL COMMENT '完成时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- milestones ----------
ALTER TABLE milestones COMMENT = '项目里程碑与阶段款';
ALTER TABLE milestones
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '里程碑 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '里程碑标题',
    MODIFY COLUMN description TEXT NULL COMMENT '说明',
    MODIFY COLUMN sort_order INT NOT NULL COMMENT '排序序号',
    MODIFY COLUMN payment_ratio DECIMAL(5,2) NULL COMMENT '付款比例',
    MODIFY COLUMN payment_amount DECIMAL(10,2) NULL COMMENT '阶段金额',
    MODIFY COLUMN due_date DATE NULL COMMENT '计划完成日',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：待交付/待验收等',
    MODIFY COLUMN delivery_note TEXT NULL COMMENT '交付说明',
    MODIFY COLUMN preview_url VARCHAR(512) NULL COMMENT '交付预览链接',
    MODIFY COLUMN rejection_reason TEXT NULL COMMENT '驳回原因',
    MODIFY COLUMN delivered_at DATETIME NULL COMMENT '交付时间',
    MODIFY COLUMN accepted_at DATETIME NULL COMMENT '验收通过时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- tasks ----------
ALTER TABLE tasks COMMENT = 'EARS 任务卡片';
ALTER TABLE tasks
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '任务 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN milestone_id BIGINT NULL COMMENT '所属里程碑',
    MODIFY COLUMN parent_task_id BIGINT NULL COMMENT '父任务 ID',
    MODIFY COLUMN task_code VARCHAR(20) NOT NULL COMMENT '任务编号',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '任务标题',
    MODIFY COLUMN ears_type VARCHAR(20) NOT NULL COMMENT 'EARS 类型 Ubiquitous/Eventual 等',
    MODIFY COLUMN ears_trigger TEXT NULL COMMENT '触发条件',
    MODIFY COLUMN ears_behavior TEXT NOT NULL COMMENT '系统行为',
    MODIFY COLUMN ears_full_text TEXT NOT NULL COMMENT '完整 EARS 描述',
    MODIFY COLUMN module VARCHAR(100) NULL COMMENT '所属模块',
    MODIFY COLUMN role_tag VARCHAR(50) NULL COMMENT '角色标签',
    MODIFY COLUMN assignee_id BIGINT NULL COMMENT '负责人用户 ID',
    MODIFY COLUMN priority SMALLINT NOT NULL DEFAULT 2 COMMENT '优先级',
    MODIFY COLUMN estimated_hours DECIMAL(5,1) NULL COMMENT '预估工时',
    MODIFY COLUMN actual_hours DECIMAL(5,1) NULL COMMENT '实际工时',
    MODIFY COLUMN acceptance_criteria JSON NULL COMMENT '验收标准 JSON',
    MODIFY COLUMN dependencies JSON NULL COMMENT '依赖任务 JSON',
    MODIFY COLUMN blockers JSON NULL COMMENT '阻塞项 JSON',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '任务状态',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN is_ai_generated TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否 AI 生成',
    MODIFY COLUMN ai_confidence DECIMAL(3,2) NULL COMMENT 'AI 置信度',
    MODIFY COLUMN extra JSON NULL COMMENT '扩展字段',
    MODIFY COLUMN started_at DATETIME NULL COMMENT '开始时间',
    MODIFY COLUMN completed_at DATETIME NULL COMMENT '完成时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- bids ----------
ALTER TABLE bids COMMENT = '项目投标';
ALTER TABLE bids
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '投标 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN bidder_id BIGINT NULL COMMENT '投标专家用户 ID',
    MODIFY COLUMN team_id BIGINT NULL COMMENT '投标团队 ID',
    MODIFY COLUMN price DECIMAL(10,2) NOT NULL COMMENT '报价金额',
    MODIFY COLUMN estimated_days INT NOT NULL COMMENT '预估工期天数',
    MODIFY COLUMN proposal TEXT NULL COMMENT '方案说明',
    MODIFY COLUMN tech_solution TEXT NULL COMMENT '技术方案',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：待处理/中标/落选等',
    MODIFY COLUMN reject_reason VARCHAR(200) NULL COMMENT '拒绝原因',
    MODIFY COLUMN accepted_at DATETIME NULL COMMENT '中标时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- orders ----------
ALTER TABLE orders COMMENT = '订单与托管支付';
ALTER TABLE orders
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '订单 UUID',
    MODIFY COLUMN order_no VARCHAR(32) NOT NULL COMMENT '业务订单号',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN milestone_id BIGINT NULL COMMENT '关联里程碑（分期时）',
    MODIFY COLUMN payer_id BIGINT NOT NULL COMMENT '付款方用户 ID',
    MODIFY COLUMN payee_id BIGINT NULL COMMENT '收款方用户 ID',
    MODIFY COLUMN payee_team_id BIGINT NULL COMMENT '收款团队 ID',
    MODIFY COLUMN amount DECIMAL(10,2) NOT NULL COMMENT '项目款金额',
    MODIFY COLUMN platform_fee_rate DECIMAL(5,4) NOT NULL DEFAULT 0.1200 COMMENT '平台佣金率',
    MODIFY COLUMN platform_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '平台服务费金额',
    MODIFY COLUMN actual_amount DECIMAL(10,2) NULL COMMENT '实付金额（含优惠等）',
    MODIFY COLUMN payment_method VARCHAR(20) NULL COMMENT '支付方式',
    MODIFY COLUMN trade_no VARCHAR(64) NULL COMMENT '第三方支付流水号',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '订单状态：待支付/已付/完成等',
    MODIFY COLUMN refund_amount DECIMAL(10,2) NULL COMMENT '退款金额',
    MODIFY COLUMN refund_reason VARCHAR(200) NULL COMMENT '退款原因',
    MODIFY COLUMN refund_trade_no VARCHAR(64) NULL COMMENT '退款流水号',
    MODIFY COLUMN paid_at DATETIME NULL COMMENT '支付时间',
    MODIFY COLUMN escrow_at DATETIME NULL COMMENT '进入托管时间',
    MODIFY COLUMN released_at DATETIME NULL COMMENT '释放给服务方时间',
    MODIFY COLUMN withdrawn_at DATETIME NULL COMMENT '提现完成时间',
    MODIFY COLUMN refunded_at DATETIME NULL COMMENT '退款完成时间',
    MODIFY COLUMN expire_at DATETIME NULL COMMENT '订单过期时间',
    MODIFY COLUMN auto_release_at DATETIME NULL COMMENT '自动确认释放时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- split_records ----------
ALTER TABLE split_records COMMENT = '订单团队内分账明细';
ALTER TABLE split_records
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '记录 UUID',
    MODIFY COLUMN order_id BIGINT NOT NULL COMMENT '订单 ID',
    MODIFY COLUMN team_id BIGINT NOT NULL COMMENT '团队 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '成员用户 ID',
    MODIFY COLUMN split_ratio DECIMAL(5,2) NOT NULL COMMENT '分账比例',
    MODIFY COLUMN amount DECIMAL(10,2) NOT NULL COMMENT '分账金额',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '分账状态',
    MODIFY COLUMN split_at DATETIME NULL COMMENT '分账执行时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- wallets ----------
ALTER TABLE wallets COMMENT = '用户钱包余额';
ALTER TABLE wallets
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN available_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '可用余额',
    MODIFY COLUMN frozen_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '冻结余额',
    MODIFY COLUMN total_income DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计收入',
    MODIFY COLUMN total_withdrawn DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计提现',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- wallet_transactions ----------
ALTER TABLE wallet_transactions COMMENT = '钱包流水';
ALTER TABLE wallet_transactions
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '流水 UUID',
    MODIFY COLUMN wallet_id BIGINT NOT NULL COMMENT '钱包 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN order_id BIGINT NULL COMMENT '关联订单',
    MODIFY COLUMN transaction_type SMALLINT NOT NULL COMMENT '交易类型：收入/提现等',
    MODIFY COLUMN amount DECIMAL(10,2) NOT NULL COMMENT '变动金额',
    MODIFY COLUMN balance_before DECIMAL(12,2) NOT NULL COMMENT '变动前余额',
    MODIFY COLUMN balance_after DECIMAL(12,2) NOT NULL COMMENT '变动后余额',
    MODIFY COLUMN withdraw_method VARCHAR(20) NULL COMMENT '提现方式',
    MODIFY COLUMN withdraw_account VARCHAR(200) NULL COMMENT '提现账户信息',
    MODIFY COLUMN withdraw_trade_no VARCHAR(64) NULL COMMENT '提现通道流水号',
    MODIFY COLUMN remark VARCHAR(200) NULL COMMENT '备注',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '流水状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- conversations ----------
ALTER TABLE conversations COMMENT = '单聊/项目会话';
ALTER TABLE conversations
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '会话 UUID',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '关联项目',
    MODIFY COLUMN conversation_type SMALLINT NOT NULL DEFAULT 1 COMMENT '会话类型',
    MODIFY COLUMN user_a_id BIGINT NULL COMMENT '参与者 A 用户 ID（较小 ID 侧约定）',
    MODIFY COLUMN user_b_id BIGINT NULL COMMENT '参与者 B 用户 ID',
    MODIFY COLUMN last_message_content VARCHAR(200) NULL COMMENT '最后一条消息摘要',
    MODIFY COLUMN last_message_type VARCHAR(20) NULL COMMENT '最后消息类型',
    MODIFY COLUMN last_message_at DATETIME NULL COMMENT '最后消息时间',
    MODIFY COLUMN last_message_user_id BIGINT NULL COMMENT '最后发送人',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '会话状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- conversation_members ----------
ALTER TABLE conversation_members COMMENT = '会话成员（扩展用，含未读）';
ALTER TABLE conversation_members
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN conversation_id BIGINT NOT NULL COMMENT '会话 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN role SMALLINT NOT NULL DEFAULT 1 COMMENT '在会话中的角色',
    MODIFY COLUMN unread_count INT NOT NULL DEFAULT 0 COMMENT '未读条数',
    MODIFY COLUMN last_read_msg_id BIGINT NULL DEFAULT 0 COMMENT '最后已读消息 ID',
    MODIFY COLUMN is_muted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否免打扰',
    MODIFY COLUMN is_pinned TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否置顶',
    MODIFY COLUMN joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间';

-- ---------- messages ----------
ALTER TABLE messages COMMENT = '聊天消息';
ALTER TABLE messages
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '消息 UUID',
    MODIFY COLUMN conversation_id BIGINT NOT NULL COMMENT '会话 ID',
    MODIFY COLUMN sender_id BIGINT NOT NULL COMMENT '发送者用户 ID',
    MODIFY COLUMN content_type VARCHAR(20) NOT NULL DEFAULT 'text' COMMENT '内容类型 text/image/system 等',
    MODIFY COLUMN content TEXT NULL COMMENT '文本内容',
    MODIFY COLUMN media_url VARCHAR(512) NULL COMMENT '媒体 URL',
    MODIFY COLUMN media_name VARCHAR(200) NULL COMMENT '媒体文件名',
    MODIFY COLUMN media_size INT NULL COMMENT '媒体大小字节',
    MODIFY COLUMN media_duration INT NULL COMMENT '音视频时长秒',
    MODIFY COLUMN thumbnail_url VARCHAR(512) NULL COMMENT '缩略图 URL',
    MODIFY COLUMN reply_to_msg_id BIGINT NULL COMMENT '回复的消息 ID',
    MODIFY COLUMN related_task_id BIGINT NULL COMMENT '关联任务 ID',
    MODIFY COLUMN client_seq BIGINT NULL COMMENT '客户端序号去重',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '消息状态',
    MODIFY COLUMN recalled_at DATETIME NULL COMMENT '撤回时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间';

-- ---------- reviews ----------
ALTER TABLE reviews COMMENT = '双向评价';
ALTER TABLE reviews
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '评价 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN reviewer_id BIGINT NOT NULL COMMENT '评价人用户 ID',
    MODIFY COLUMN reviewee_id BIGINT NOT NULL COMMENT '被评价人用户 ID',
    MODIFY COLUMN reviewer_role SMALLINT NOT NULL COMMENT '评价人角色（需求方/服务方）',
    MODIFY COLUMN overall_rating DECIMAL(2,1) NOT NULL COMMENT '综合星级',
    MODIFY COLUMN quality_rating DECIMAL(2,1) NULL COMMENT '质量',
    MODIFY COLUMN communication_rating DECIMAL(2,1) NULL COMMENT '沟通',
    MODIFY COLUMN timeliness_rating DECIMAL(2,1) NULL COMMENT '时效',
    MODIFY COLUMN professionalism_rating DECIMAL(2,1) NULL COMMENT '专业度',
    MODIFY COLUMN requirement_clarity DECIMAL(2,1) NULL COMMENT '需求清晰度（评需求方）',
    MODIFY COLUMN payment_rating DECIMAL(2,1) NULL COMMENT '付款及时性',
    MODIFY COLUMN cooperation_rating DECIMAL(2,1) NULL COMMENT '配合度',
    MODIFY COLUMN content TEXT NULL COMMENT '文字评价',
    MODIFY COLUMN tags JSON NULL COMMENT '标签 JSON',
    MODIFY COLUMN member_ratings JSON NULL COMMENT '团队成员子评分 JSON',
    MODIFY COLUMN is_anonymous TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否匿名',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '评价状态',
    MODIFY COLUMN reply_content TEXT NULL COMMENT '对方回复',
    MODIFY COLUMN reply_at DATETIME NULL COMMENT '回复时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- notifications ----------
ALTER TABLE notifications COMMENT = '站内通知';
ALTER TABLE notifications
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '通知 UUID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '接收用户 ID',
    MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '正文',
    MODIFY COLUMN notification_type SMALLINT NOT NULL COMMENT '类型：撮合/支付提醒等业务枚举',
    MODIFY COLUMN target_type VARCHAR(50) NULL COMMENT '关联实体类型 project/order 等',
    MODIFY COLUMN target_id BIGINT NULL COMMENT '关联实体 ID',
    MODIFY COLUMN is_read TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已读',
    MODIFY COLUMN is_pushed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已推送',
    MODIFY COLUMN push_result VARCHAR(200) NULL COMMENT '推送结果说明',
    MODIFY COLUMN read_at DATETIME NULL COMMENT '已读时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- reports ----------
ALTER TABLE reports COMMENT = '用户举报';
ALTER TABLE reports
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '举报 UUID',
    MODIFY COLUMN reporter_id BIGINT NOT NULL COMMENT '举报人用户 ID',
    MODIFY COLUMN target_type VARCHAR(50) NOT NULL COMMENT '被举报对象类型',
    MODIFY COLUMN target_id BIGINT NOT NULL COMMENT '被举报对象 ID',
    MODIFY COLUMN reason_type SMALLINT NOT NULL COMMENT '举报原因分类',
    MODIFY COLUMN reason_detail TEXT NULL COMMENT '详细说明',
    MODIFY COLUMN evidence JSON NULL COMMENT '证据附件 JSON',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '处理状态',
    MODIFY COLUMN handler_id BIGINT NULL COMMENT '处理人管理员 ID',
    MODIFY COLUMN handle_result TEXT NULL COMMENT '处理结果',
    MODIFY COLUMN handled_at DATETIME NULL COMMENT '处理时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- arbitrations ----------
ALTER TABLE arbitrations COMMENT = '纠纷仲裁';
ALTER TABLE arbitrations
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '仲裁 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN order_id BIGINT NULL COMMENT '关联订单',
    MODIFY COLUMN applicant_id BIGINT NOT NULL COMMENT '申请人用户 ID',
    MODIFY COLUMN respondent_id BIGINT NOT NULL COMMENT '被申请人用户 ID',
    MODIFY COLUMN reason TEXT NOT NULL COMMENT '申请理由',
    MODIFY COLUMN evidence JSON NULL COMMENT '证据 JSON',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '仲裁状态',
    MODIFY COLUMN arbiter_id BIGINT NULL COMMENT '仲裁员/管理员 ID',
    MODIFY COLUMN verdict TEXT NULL COMMENT '裁决说明',
    MODIFY COLUMN verdict_type SMALLINT NULL COMMENT '裁决类型',
    MODIFY COLUMN refund_amount DECIMAL(10,2) NULL COMMENT '裁定退款金额',
    MODIFY COLUMN arbitrated_at DATETIME NULL COMMENT '裁决时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- agent_sessions ----------
ALTER TABLE agent_sessions COMMENT = 'AI 需求分析会话';
ALTER TABLE agent_sessions
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '会话 UUID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '关联项目',
    MODIFY COLUMN agent_type VARCHAR(50) NOT NULL COMMENT 'Agent 类型',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '会话状态',
    MODIFY COLUMN completeness_score DECIMAL(5,2) NULL DEFAULT 0.00 COMMENT '需求完整度得分',
    MODIFY COLUMN conversation_history JSON NULL COMMENT '对话历史 JSON',
    MODIFY COLUMN generated_prd JSON NULL COMMENT '生成的 PRD',
    MODIFY COLUMN generated_tasks JSON NULL COMMENT '生成的任务',
    MODIFY COLUMN generated_estimate JSON NULL COMMENT '生成的估价',
    MODIFY COLUMN model_used VARCHAR(50) NULL COMMENT '使用的模型名',
    MODIFY COLUMN total_tokens INT NULL DEFAULT 0 COMMENT '累计 Token',
    MODIFY COLUMN total_cost DECIMAL(8,4) NULL DEFAULT 0.0000 COMMENT '累计费用',
    MODIFY COLUMN completed_at DATETIME NULL COMMENT '完成时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- coupons ----------
ALTER TABLE coupons COMMENT = '用户优惠券';
ALTER TABLE coupons
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '券 UUID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN title VARCHAR(100) NOT NULL COMMENT '券名称',
    MODIFY COLUMN discount_amount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
    MODIFY COLUMN min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '最低订单金额门槛',
    MODIFY COLUMN expire_date DATE NOT NULL COMMENT '过期日期',
    MODIFY COLUMN is_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已使用',
    MODIFY COLUMN used_at DATETIME NULL COMMENT '使用时间',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '券状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '领取时间';

-- ---------- matches ----------
ALTER TABLE matches COMMENT = 'AI/系统匹配推荐记录';
ALTER TABLE matches
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '记录 UUID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目 ID',
    MODIFY COLUMN expert_id BIGINT NULL COMMENT '推荐专家用户 ID',
    MODIFY COLUMN team_id BIGINT NULL COMMENT '推荐团队 ID',
    MODIFY COLUMN match_score DECIMAL(5,2) NULL COMMENT '匹配得分',
    MODIFY COLUMN match_reason JSON NULL COMMENT '匹配理由 JSON',
    MODIFY COLUMN is_ai_matched TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否 AI 匹配',
    MODIFY COLUMN status SMALLINT NOT NULL DEFAULT 1 COMMENT '记录状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ---------- invite_codes ----------
ALTER TABLE invite_codes COMMENT = '注册/团队邀请码';
ALTER TABLE invite_codes
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '记录 UUID',
    MODIFY COLUMN team_id BIGINT NULL COMMENT '所属团队，核销后新码仍属同一团队',
    MODIFY COLUMN code_hash VARCHAR(64) NOT NULL COMMENT '码明文哈希，用于校验',
    MODIFY COLUMN code_plain VARCHAR(32) NULL COMMENT '当前有效码明文（管理端展示）',
    MODIFY COLUMN code_hint VARCHAR(20) NOT NULL DEFAULT '' COMMENT '码尾号提示',
    MODIFY COLUMN note VARCHAR(200) NULL DEFAULT '' COMMENT '备注',
    MODIFY COLUMN max_uses INT NOT NULL DEFAULT 1 COMMENT '最大使用次数',
    MODIFY COLUMN used_count INT NOT NULL DEFAULT 0 COMMENT '已使用次数',
    MODIFY COLUMN expires_at DATETIME NULL COMMENT '过期时间',
    MODIFY COLUMN allowed_roles JSON NULL COMMENT '允许注册的角色列表，空表示不限制',
    MODIFY COLUMN disabled_at DATETIME NULL COMMENT '停用时间',
    MODIFY COLUMN created_by_user_id BIGINT NULL COMMENT '创建人管理员用户 ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ---------- team_static_assets ----------
ALTER TABLE team_static_assets COMMENT = '团队静态资源元数据（文件在对象存储）';
ALTER TABLE team_static_assets
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN uuid VARCHAR(36) NOT NULL COMMENT '资产 UUID',
    MODIFY COLUMN team_id BIGINT NOT NULL COMMENT '团队 ID',
    MODIFY COLUMN uploaded_by_user_id BIGINT NOT NULL COMMENT '上传人用户 ID',
    MODIFY COLUMN bucket VARCHAR(128) NOT NULL COMMENT '对象存储桶名',
    MODIFY COLUMN object_key VARCHAR(512) NOT NULL COMMENT '对象键路径',
    MODIFY COLUMN original_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '原始文件名',
    MODIFY COLUMN content_type VARCHAR(128) NOT NULL DEFAULT 'application/octet-stream' COMMENT 'MIME 类型',
    MODIFY COLUMN size_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小字节',
    MODIFY COLUMN purpose VARCHAR(64) NOT NULL DEFAULT 'content' COMMENT '用途：content/avatar/doc 等',
    MODIFY COLUMN storage VARCHAR(32) NOT NULL DEFAULT 'minio' COMMENT '存储后端标识',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
